language: minimal
os: linux
dist: focal
addons:
  apt:
    packages:
    - python3-pip


install:
  - sudo pip3 install -U pip
  - sudo pip3 install --require-hashes -r devel-requirements.txt

script: python3 tests/lint


notifications:
  email:
    recipients:
      - scott@rerobots.net
    on_success: change
    on_failure: always
